title: James Brusey
description: Professor of Computer Science
url: "https://jbrusey.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "James Brusey"
  bio: "Professor of Computer Science"

markdown: kramdown
words_per_minute: 150